### ISSUE TITLE
Internet Connection

### ISSUE THREAD

**Issue by FerreiraPSM** [r-lib/pingr#10]
Can I use some pingr function to leave my RStudio online? When I use the is.online () command, the answer is FALSE.

**Comment by gaborcsardi** [comment]
I am not sure what you mean. You mean your machine goes offline by itself somehow?

**Comment by FerreiraPSM** [comment]
I am trying to get some data through the wdpar package, but I have the following error message:
"Error in wdpa_fetch (" Malta ", wait = TRUE):
   data not found in download_dir, and on the internet connectionto download it. "
Probably my R is not identifying that I'm connected to the internet. I wonder if I can use some pingr function to solve this problem.

**Comment by gaborcsardi** [comment]
Not really. pingr will tell you that you are offline, but it cannot put you online.

**Comment by FerreiraPSM** [comment]
Ok, thank you.
