### ISSUE TITLE
ping fails, ping_port works

### ISSUE THREAD

**Issue by dmenne** [r-lib/pingr#15]
Windows, R 4.0.0 

```
ping("www.google.com")
[1] NA NA NA
> ping_port("www.google.com")
[1] 18.002 30.007 23.161
```
Is this "expected behavior"?

**Comment by dmenne** [comment]
``` r
system("ping www.google.com")
#> [1] 0
ping("www.google.com")
#> Error in ping("www.google.com"): konnte Funktion "ping" nicht finden
ping_port("www.google.com")
#> Error in ping_port("www.google.com"): konnte Funktion "ping_port" nicht finden
```

<sup>Created on 2020-06-29 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by gaborcsardi** [comment]
Yes, that is expected, because you don't have an external ping program.

`ping()` is pretty useless nowadays, anyway. If you want to check if a web server is up, use `ping_port()`. `ping()`'s success or failure will not tell you anything about that.
