### ISSUE TITLE
Build fails on FreeBSD since `-lresolv` is not needed

### ISSUE THREAD

**Issue by yzgyyang** [r-lib/pingr#21]
`-lresolv` is not needed for FreeBSD since it is in libc. So, https://github.com/r-lib/pingr/blob/bfe03f4c34945c50a856a7c4844f642fb310193d/src/Makevars#L1 will raise an error during build. To fix it, just an empty PKG_LIBS would work, but I do not know `Makevars` enough to have a platform-specific fix there.

**Comment by gaborcsardi** [comment]
We have now a CI for FreeBSD!
